### ISSUE TITLE
ValueError: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by arjanvandervelde** [jupyter/terminado#110]
Hi!

We're running into an issue that seems to have been introduced by https://github.com/jupyter/terminado/pull/107. Upon opening a terminal window, it sometimes gets stuck in a never-ending loop, repeating the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/usr/local/lib/python3.8/site-packages/terminado/management.py", line 209, in pty_read
    r, _, _ = select.select([fd], [], [], .1)
ValueError: filedescriptor out of range in select()
...
...
```

When this happens we cannot kill the terminal from jupyter and if left unchecked it generates huge amounts of logging. We are running single-user notebooks similar to https://github.com/jupyter/terminado/issues/106. It seems that `poll()` might be a better solution here than `select()`. Our environment allows for 1M open files but `select()` can only handle 1024.

Thanks!

-- Arjan

**Comment by blink1073** [comment]
Sounds reasonable, mind opening a PR?

**Comment by arjanvandervelde** [comment]
done.
