### ISSUE TITLE
Error during pip v2.7.11 install on 0.7 and above, works on 0.6 and below. (python 2.7.14 works fine)

### ISSUE THREAD

**Issue by ssuchter** [jupyter/terminado#52]
Hi there! I've got a reproducible issue (on my environment, at least) that surrounds installing terminado via pip.

Background: I've got a process that we use to build a python environment that is relocatable between machines. It builds python in a subdirectory of the user doing the build, not in the OS installed location. I'm not sure if this is relevant or not, but seems possible.

When I run this:

.../native-env-builder/target/native-dev62-SNAPSHOT/bin/pip install --no-use-wheel -b pip-build terminado==0.7

I get this error:

> DEPRECATION: --no-use-wheel is deprecated and will be removed in the future.  Please use --no-binary :all: instead.
> Collecting terminado==0.7
>   Using cached terminado-0.7.tar.gz
> Requirement already satisfied: ptyprocess in ./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from terminado==0.7)
> Requirement already satisfied: tornado>=4 in ./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from terminado==0.7)
> Requirement already satisfied: singledispatch in ./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from tornado>=4->terminado==0.7)
> Requirement already satisfied: certifi in ./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from tornado>=4->terminado==0.7)
> Requirement already satisfied: backports_abc>=0.4 in ./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from tornado>=4->terminado==0.7)
> Requirement already satisfied: six in ./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from singledispatch->tornado>=4->terminado==0.7)
> Installing collected packages: terminado
>   Found existing installation: terminado 0.6
>     Uninstalling terminado-0.6:
>       Successfully uninstalled terminado-0.6
>   Running setup.py install for terminado ... error
>     Complete output from command /Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/bin/python -u -c "import setuptools, tokenize;__file__='/Users/ssuchter/src/pepperdata11/native-env-builder/target/pip-build/terminado/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/y6/6ccct9kd5ms1080vt5nv4jm00000gn/T/pip-PNF25V-record/install-record.txt --single-version-externally-managed --compile:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib
>     creating build/lib/terminado
>     copying terminado/__init__.py -> build/lib/terminado
>     copying terminado/management.py -> build/lib/terminado
>     copying terminado/uimodule.py -> build/lib/terminado
>     copying terminado/websocket.py -> build/lib/terminado
>     creating build/lib/terminado/tests
>     copying terminado/tests/__init__.py -> build/lib/terminado/tests
>     copying terminado/tests/basic_test.py -> build/lib/terminado/tests
>     error: can't copy 'terminado/_static': doesn't exist or not a regular file
> 
>     ----------------------------------------
>   Rolling back uninstall of terminado
> Command "/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/bin/python -u -c "import setuptools, tokenize;__file__='/Users/ssuchter/src/pepperdata11/native-env-builder/target/pip-build/terminado/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/y6/6ccct9kd5ms1080vt5nv4jm00000gn/T/pip-PNF25V-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /Users/ssuchter/src/pepperdata11/native-env-builder/target/pip-build/terminado/
> 

But when I run this:

.../native-env-builder/target/native-dev62-SNAPSHOT/bin/pip install --no-use-wheel -b pip-build terminado==0.6

everything works:

> DEPRECATION: --no-use-wheel is deprecated and will be removed in the future.  Please use --no-binary :all: instead.
> Collecting terminado==0.6
>   Using cached terminado-0.6.tar.gz
> Requirement already satisfied: ptyprocess in ./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from terminado==0.6)
> Requirement already satisfied: tornado>=4 in ./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from terminado==0.6)
> Requirement already satisfied: singledispatch in ./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from tornado>=4->terminado==0.6)
> Requirement already satisfied: certifi in ./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from tornado>=4->terminado==0.6)
> Requirement already satisfied: backports_abc>=0.4 in ./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from tornado>=4->terminado==0.6)
> Requirement already satisfied: six in ./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from singledispatch->tornado>=4->terminado==0.6)
> Installing collected packages: terminado
>   Running setup.py install for terminado ... done
> Successfully installed terminado-0.6
> 

For now, I'm going to use 0.6, but I thought I'd like to let you know about the issue.

**Comment by payne92** [comment]
I'm wondering about this error in your 0.6 version install:

> Running setup.py install for terminado ... error
> Complete output from command /Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/bin/python -u -c "import setuptools, tokenize;file='/Users/ssuchter/src/pepperdata11/native-env-builder/target/pip-build/terminado/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /var/folders/y6/6ccct9kd5ms1080vt5nv4jm00000gn/T/pip-PNF25V-record/install-record.txt --single-version-externally-managed --compile:

If you try your 0.7 version install with the --verbose option, what does same command look like for a successful install?   I'm also wondering about the /var/folders/y6... path -- does the user you're installing with have read/write permisssions to that path and file?

I can't yet reproduce the problem on my system.  0.6 and 0.7 happily install with pip (version 9.0.1) but I note that my versions of the above command have paths that point to /tmp, not /var/folders.

**Comment by takluyver** [comment]
I also just tried `pip install --no-use-wheel -b pip-build terminado==0.7` in a fresh environment, and it ran happily. Not sure where to go on debugging that.

**Comment by ssuchter** [comment]
I totally believe it is something about my environment.


*0.6 (successful) with —verbose:*

DEPRECATION: --no-use-wheel is deprecated and will be removed in the
future.  Please use --no-binary :all: instead.
Collecting terminado==0.6
  1 location(s) to search for versions of terminado:
  * https://pypi.python.org/simple/terminado/
  Getting page https://pypi.python.org/simple/terminado/
  Looking up "https://pypi.python.org/simple/terminado/" in the cache
  Current age based on date: 151
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 151
  Analyzing links from page https://pypi.python.org/simple/terminado/
    Found link
https://pypi.python.org/packages/07/d6/cc8e11e4bbb2127f8b6447d9fd2ce77a46f33cbeb5c6fe155f8ccc3ae7a7/terminado-0.3.3.tar.gz#md5=51e339c0e8dd1d11f6d6ad033b11acab
(from https://pypi.python.org/simple/terminado/), version: 0.3.3
    Found link
https://pypi.python.org/packages/0a/f4/98c52734d005ca8186fca3ae4bcca2e806c2d133c077123f2f36648f35cc/terminado-0.4.tar.gz#md5=ca2a6347cb6faf995baab1f64c21f40e
(from https://pypi.python.org/simple/terminado/), version: 0.4
    Skipping link
https://pypi.python.org/packages/1c/e7/2e0db4a19ef1ec0bc492cfde9a5c2c6a9cd09569eb1934fcc7cf17a0f2f8/terminado-0.7-py2.py3-none-any.whl#md5=af1714d4157697b6f26691ebd31dc885
(from https://pypi.python.org/simple/terminado/); No binaries permitted for
terminado
    Skipping link
https://pypi.python.org/packages/2e/20/a26211a24425923d46e1213b376a6ee60dc30bcdf1b0c345e2c3769deb1c/terminado-0.8.1-py2.py3-none-any.whl#md5=fa63b4f05641d97ee363ed5feb6d3b22
(from https://pypi.python.org/simple/terminado/); No binaries permitted for
terminado
    Found link
https://pypi.python.org/packages/4e/87/62a8a8da7cacb3b85f22e4665cbedec7d44e97adb551129202a3fb69475a/terminado-0.3.1.tar.gz#md5=983247bfc513a6aa71a67fde0944b334
(from https://pypi.python.org/simple/terminado/), version: 0.3.1
    Found link
https://pypi.python.org/packages/58/59/aabe84fce2f45da10165435cec204d982863e176f6849a4a4fe2652a20a8/terminado-0.6.tar.gz#md5=5b6c65da27fe1ed07a9f80f0588cdaba
(from https://pypi.python.org/simple/terminado/), version: 0.6
    Found link
https://pypi.python.org/packages/67/84/ce0ebd0f60e1cbe040f8e065eef7063855d59d9cf5e6438b3f8439fc7e15/terminado-0.8.1.tar.gz#md5=616515f562939e979b67c72b667afba9
(from https://pypi.python.org/simple/terminado/), version: 0.8.1
    Found link
https://pypi.python.org/packages/6f/b6/31371ec7e805ca2db901cc52302cd517a1bfe512b382ddbedd851dde8515/terminado-0.7.tar.gz#md5=119675884d3eba2646b577fcb0de3b3a
(from https://pypi.python.org/simple/terminado/), version: 0.7
    Found link
https://pypi.python.org/packages/8e/20/ff191e82bfa09283d24385fa0e2b4dacfd268ccf9153a3a7d3a230043594/terminado-0.3.2.tar.gz#md5=209b978863b8df6659f95acd11c3c564
(from https://pypi.python.org/simple/terminado/), version: 0.3.2
    Found link
https://pypi.python.org/packages/91/a5/129e45d6e7e597f64a7e073288724efb0b7b68954f6b16c00fada05c9d3c/terminado-0.8.tar.gz#md5=5d64a640e87f3f8135bf136989fcf6c3
(from https://pypi.python.org/simple/terminado/), version: 0.8
    Found link
https://pypi.python.org/packages/9b/fd/8dfb64877a020511461233230c442ed629bdf845792afc3d5f5f07989598/terminado-0.5.tar.gz#md5=e992c6262a5f4c8952fee93da31a067e
(from https://pypi.python.org/simple/terminado/), version: 0.5
    Skipping link
https://pypi.python.org/packages/a7/1f/23b9ced84b853bf2e5d42719a51075b6ed937d149d843d6d2a8f8ff03add/terminado-0.8-py2.py3-none-any.whl#md5=8ec5e63cda8a696e89240d1f0bfba588
(from https://pypi.python.org/simple/terminado/); No binaries permitted for
terminado
    Found link
https://pypi.python.org/packages/d5/b8/76ba9f6328ec5fd35b20bf8514bf5677dfde6880f6c838eebaf2a9a8b4ed/terminado-0.1.tar.gz#md5=1592d98b3e963d3bd6f87d475134bf6f
(from https://pypi.python.org/simple/terminado/), version: 0.1
    Found link
https://pypi.python.org/packages/d6/28/b0f9c19981d93b0cbc1e9ca01890cb2ffeca1ab1aeab1b1244d0647fe169/terminado-0.3.tar.gz#md5=e05175894cd5ce384bb94833df37b8a0
(from https://pypi.python.org/simple/terminado/), version: 0.3
    Found link
https://pypi.python.org/packages/fe/8f/00a354a0f45d96db4208db488d4afb4a8d25c30379bbe90f2879aff73558/terminado-0.2.tar.gz#md5=1b20a13c1c01f308ed09a6cd7f77d4b6
(from https://pypi.python.org/simple/terminado/), version: 0.2
  Using version 0.6 (newest of versions: 0.6)
  Looking up "
https://pypi.python.org/packages/58/59/aabe84fce2f45da10165435cec204d982863e176f6849a4a4fe2652a20a8/terminado-0.6.tar.gz"
in the cache
  Current age based on date: 27212176
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 27212176
  Using cached terminado-0.6.tar.gz
  Downloading from URL
https://pypi.python.org/packages/58/59/aabe84fce2f45da10165435cec204d982863e176f6849a4a4fe2652a20a8/terminado-0.6.tar.gz#md5=5b6c65da27fe1ed07a9f80f0588cdaba
(from https://pypi.python.org/simple/terminado/)
  Running setup.py
(path:/Users/ssuchter/src/pepperdata11/native-env-builder/target/pip-build/terminado/setup.py)
egg_info for package terminado
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/terminado.egg-info
    writing requirements to pip-egg-info/terminado.egg-info/requires.txt
    writing pip-egg-info/terminado.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/terminado.egg-info/top_level.txt
    writing dependency_links to
pip-egg-info/terminado.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/terminado.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/terminado.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/terminado.egg-info/SOURCES.txt'
  Source in ./pip-build/terminado has version 0.6, which satisfies
requirement terminado==0.6 from
https://pypi.python.org/packages/58/59/aabe84fce2f45da10165435cec204d982863e176f6849a4a4fe2652a20a8/terminado-0.6.tar.gz#md5=5b6c65da27fe1ed07a9f80f0588cdaba
Requirement already satisfied: ptyprocess in
./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from terminado==0.6)
Requirement already satisfied: tornado>=4 in
./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from terminado==0.6)
Requirement already satisfied: singledispatch in
./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from
tornado>=4->terminado==0.6)
Requirement already satisfied: certifi in
./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from
tornado>=4->terminado==0.6)
Requirement already satisfied: backports_abc>=0.4 in
./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from
tornado>=4->terminado==0.6)
Requirement already satisfied: six in
./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from
singledispatch->tornado>=4->terminado==0.6)
Installing collected packages: terminado
  Running setup.py install for terminado ...     Running command
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/bin/python
-u -c "import setuptools,
tokenize;__file__='/Users/ssuchter/src/pepperdata11/native-env-builder/target/pip-build/terminado/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
/var/folders/y6/6ccct9kd5ms1080vt5nv4jm00000gn/T/pip-qAQHDG-record/install-record.txt
--single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/terminado
    copying terminado/__init__.py -> build/lib/terminado
    copying terminado/management.py -> build/lib/terminado
    copying terminado/uimodule.py -> build/lib/terminado
    copying terminado/websocket.py -> build/lib/terminado
    creating build/lib/terminado/tests
    copying terminado/tests/__init__.py -> build/lib/terminado/tests
    copying terminado/tests/basic_test.py -> build/lib/terminado/tests
    copying terminado/uimod_embed.js -> build/lib/terminado
    creating build/lib/terminado/_static
    copying terminado/_static/terminado.js -> build/lib/terminado/_static
    running install_lib
    creating
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado
    copying build/lib/terminado/__init__.py ->
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado
    creating
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado/_static
    copying build/lib/terminado/_static/terminado.js ->
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado/_static
    copying build/lib/terminado/management.py ->
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado
    creating
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado/tests
    copying build/lib/terminado/tests/__init__.py ->
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado/tests
    copying build/lib/terminado/tests/basic_test.py ->
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado/tests
    copying build/lib/terminado/uimod_embed.js ->
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado
    copying build/lib/terminado/uimodule.py ->
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado
    copying build/lib/terminado/websocket.py ->
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado
    byte-compiling
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado/__init__.py
to __init__.pyc
    byte-compiling
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado/management.py
to management.pyc
    byte-compiling
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado/tests/__init__.py
to __init__.pyc
    byte-compiling
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado/tests/basic_test.py
to basic_test.pyc
    byte-compiling
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado/uimodule.py
to uimodule.pyc
    byte-compiling
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado/websocket.py
to websocket.pyc
    running install_egg_info
    running egg_info
    creating terminado.egg-info
    writing requirements to terminado.egg-info/requires.txt
    writing terminado.egg-info/PKG-INFO
    writing top-level names to terminado.egg-info/top_level.txt
    writing dependency_links to terminado.egg-info/dependency_links.txt
    writing manifest file 'terminado.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'terminado.egg-info/SOURCES.txt'
    writing manifest file 'terminado.egg-info/SOURCES.txt'
    Copying terminado.egg-info to
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/terminado-0.6-py2.7.egg-info
    running install_scripts
    writing list of installed files to
'/var/folders/y6/6ccct9kd5ms1080vt5nv4jm00000gn/T/pip-qAQHDG-record/install-record.txt'
done
  Removing source in
/Users/ssuchter/src/pepperdata11/native-env-builder/target/pip-build/terminado
Successfully installed terminado-0.6
Cleaning up…



*0.7 (unsuccessful) with verbose:*

DEPRECATION: --no-use-wheel is deprecated and will be removed in the
future.  Please use --no-binary :all: instead.
Collecting terminado==0.7
  1 location(s) to search for versions of terminado:
  * https://pypi.python.org/simple/terminado/
  Getting page https://pypi.python.org/simple/terminado/
  Looking up "https://pypi.python.org/simple/terminado/" in the cache
  Current age based on date: 87
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 87
  Analyzing links from page https://pypi.python.org/simple/terminado/
    Found link
https://pypi.python.org/packages/07/d6/cc8e11e4bbb2127f8b6447d9fd2ce77a46f33cbeb5c6fe155f8ccc3ae7a7/terminado-0.3.3.tar.gz#md5=51e339c0e8dd1d11f6d6ad033b11acab
(from https://pypi.python.org/simple/terminado/), version: 0.3.3
    Found link
https://pypi.python.org/packages/0a/f4/98c52734d005ca8186fca3ae4bcca2e806c2d133c077123f2f36648f35cc/terminado-0.4.tar.gz#md5=ca2a6347cb6faf995baab1f64c21f40e
(from https://pypi.python.org/simple/terminado/), version: 0.4
    Skipping link
https://pypi.python.org/packages/1c/e7/2e0db4a19ef1ec0bc492cfde9a5c2c6a9cd09569eb1934fcc7cf17a0f2f8/terminado-0.7-py2.py3-none-any.whl#md5=af1714d4157697b6f26691ebd31dc885
(from https://pypi.python.org/simple/terminado/); No binaries permitted for
terminado
    Skipping link
https://pypi.python.org/packages/2e/20/a26211a24425923d46e1213b376a6ee60dc30bcdf1b0c345e2c3769deb1c/terminado-0.8.1-py2.py3-none-any.whl#md5=fa63b4f05641d97ee363ed5feb6d3b22
(from https://pypi.python.org/simple/terminado/); No binaries permitted for
terminado
    Found link
https://pypi.python.org/packages/4e/87/62a8a8da7cacb3b85f22e4665cbedec7d44e97adb551129202a3fb69475a/terminado-0.3.1.tar.gz#md5=983247bfc513a6aa71a67fde0944b334
(from https://pypi.python.org/simple/terminado/), version: 0.3.1
    Found link
https://pypi.python.org/packages/58/59/aabe84fce2f45da10165435cec204d982863e176f6849a4a4fe2652a20a8/terminado-0.6.tar.gz#md5=5b6c65da27fe1ed07a9f80f0588cdaba
(from https://pypi.python.org/simple/terminado/), version: 0.6
    Found link
https://pypi.python.org/packages/67/84/ce0ebd0f60e1cbe040f8e065eef7063855d59d9cf5e6438b3f8439fc7e15/terminado-0.8.1.tar.gz#md5=616515f562939e979b67c72b667afba9
(from https://pypi.python.org/simple/terminado/), version: 0.8.1
    Found link
https://pypi.python.org/packages/6f/b6/31371ec7e805ca2db901cc52302cd517a1bfe512b382ddbedd851dde8515/terminado-0.7.tar.gz#md5=119675884d3eba2646b577fcb0de3b3a
(from https://pypi.python.org/simple/terminado/), version: 0.7
    Found link
https://pypi.python.org/packages/8e/20/ff191e82bfa09283d24385fa0e2b4dacfd268ccf9153a3a7d3a230043594/terminado-0.3.2.tar.gz#md5=209b978863b8df6659f95acd11c3c564
(from https://pypi.python.org/simple/terminado/), version: 0.3.2
    Found link
https://pypi.python.org/packages/91/a5/129e45d6e7e597f64a7e073288724efb0b7b68954f6b16c00fada05c9d3c/terminado-0.8.tar.gz#md5=5d64a640e87f3f8135bf136989fcf6c3
(from https://pypi.python.org/simple/terminado/), version: 0.8
    Found link
https://pypi.python.org/packages/9b/fd/8dfb64877a020511461233230c442ed629bdf845792afc3d5f5f07989598/terminado-0.5.tar.gz#md5=e992c6262a5f4c8952fee93da31a067e
(from https://pypi.python.org/simple/terminado/), version: 0.5
    Skipping link
https://pypi.python.org/packages/a7/1f/23b9ced84b853bf2e5d42719a51075b6ed937d149d843d6d2a8f8ff03add/terminado-0.8-py2.py3-none-any.whl#md5=8ec5e63cda8a696e89240d1f0bfba588
(from https://pypi.python.org/simple/terminado/); No binaries permitted for
terminado
    Found link
https://pypi.python.org/packages/d5/b8/76ba9f6328ec5fd35b20bf8514bf5677dfde6880f6c838eebaf2a9a8b4ed/terminado-0.1.tar.gz#md5=1592d98b3e963d3bd6f87d475134bf6f
(from https://pypi.python.org/simple/terminado/), version: 0.1
    Found link
https://pypi.python.org/packages/d6/28/b0f9c19981d93b0cbc1e9ca01890cb2ffeca1ab1aeab1b1244d0647fe169/terminado-0.3.tar.gz#md5=e05175894cd5ce384bb94833df37b8a0
(from https://pypi.python.org/simple/terminado/), version: 0.3
    Found link
https://pypi.python.org/packages/fe/8f/00a354a0f45d96db4208db488d4afb4a8d25c30379bbe90f2879aff73558/terminado-0.2.tar.gz#md5=1b20a13c1c01f308ed09a6cd7f77d4b6
(from https://pypi.python.org/simple/terminado/), version: 0.2
  Using version 0.7 (newest of versions: 0.7)
  Looking up "
https://pypi.python.org/packages/6f/b6/31371ec7e805ca2db901cc52302cd517a1bfe512b382ddbedd851dde8515/terminado-0.7.tar.gz"
in the cache
  Current age based on date: 58056
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 58056
  Using cached terminado-0.7.tar.gz
  Downloading from URL
https://pypi.python.org/packages/6f/b6/31371ec7e805ca2db901cc52302cd517a1bfe512b382ddbedd851dde8515/terminado-0.7.tar.gz#md5=119675884d3eba2646b577fcb0de3b3a
(from https://pypi.python.org/simple/terminado/)
  Running setup.py
(path:/Users/ssuchter/src/pepperdata11/native-env-builder/target/pip-build/terminado/setup.py)
egg_info for package terminado
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/terminado.egg-info
    writing requirements to pip-egg-info/terminado.egg-info/requires.txt
    writing pip-egg-info/terminado.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/terminado.egg-info/top_level.txt
    writing dependency_links to
pip-egg-info/terminado.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/terminado.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/terminado.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/terminado.egg-info/SOURCES.txt'
  Source in ./pip-build/terminado has version 0.7, which satisfies
requirement terminado==0.7 from
https://pypi.python.org/packages/6f/b6/31371ec7e805ca2db901cc52302cd517a1bfe512b382ddbedd851dde8515/terminado-0.7.tar.gz#md5=119675884d3eba2646b577fcb0de3b3a
Requirement already satisfied: ptyprocess in
./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from terminado==0.7)
Requirement already satisfied: tornado>=4 in
./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from terminado==0.7)
Requirement already satisfied: singledispatch in
./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from
tornado>=4->terminado==0.7)
Requirement already satisfied: certifi in
./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from
tornado>=4->terminado==0.7)
Requirement already satisfied: backports_abc>=0.4 in
./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from
tornado>=4->terminado==0.7)
Requirement already satisfied: six in
./native-dev62-SNAPSHOT/lib/python2.7/site-packages (from
singledispatch->tornado>=4->terminado==0.7)
Installing collected packages: terminado
  Running setup.py install for terminado ...     Running command
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/bin/python
-u -c "import setuptools,
tokenize;__file__='/Users/ssuchter/src/pepperdata11/native-env-builder/target/pip-build/terminado/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
/var/folders/y6/6ccct9kd5ms1080vt5nv4jm00000gn/T/pip-mg9jBL-record/install-record.txt
--single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/terminado
    copying terminado/__init__.py -> build/lib/terminado
    copying terminado/management.py -> build/lib/terminado
    copying terminado/uimodule.py -> build/lib/terminado
    copying terminado/websocket.py -> build/lib/terminado
    creating build/lib/terminado/tests
    copying terminado/tests/__init__.py -> build/lib/terminado/tests
    copying terminado/tests/basic_test.py -> build/lib/terminado/tests
    error: can't copy 'terminado/_static': doesn't exist or not a regular
file
error
Cleaning up...
  Removing source in
/Users/ssuchter/src/pepperdata11/native-env-builder/target/pip-build/terminado
Command
"/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/bin/python
-u -c "import setuptools,
tokenize;__file__='/Users/ssuchter/src/pepperdata11/native-env-builder/target/pip-build/terminado/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
/var/folders/y6/6ccct9kd5ms1080vt5nv4jm00000gn/T/pip-mg9jBL-record/install-record.txt
--single-version-externally-managed --compile" failed with error code 1 in
/Users/ssuchter/src/pepperdata11/native-env-builder/target/pip-build/terminado/
Exception information:
Traceback (most recent call last):
  File
"/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/pip/basecommand.py",
line 215, in main
    status = self.run(options, args)
  File
"/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/pip/commands/install.py",
line 342, in run
    prefix=options.prefix_path,
  File
"/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/pip/req/req_set.py",
line 784, in install
    **kwargs
  File
"/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/pip/req/req_install.py",
line 878, in install
    spinner=spinner,
  File
"/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages/pip/utils/__init__.py",
line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command
"/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/bin/python
-u -c "import setuptools,
tokenize;__file__='/Users/ssuchter/src/pepperdata11/native-env-builder/target/pip-build/terminado/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
/var/folders/y6/6ccct9kd5ms1080vt5nv4jm00000gn/T/pip-mg9jBL-record/install-record.txt
--single-version-externally-managed --compile" failed with error code 1 in
/Users/ssuchter/src/pepperdata11/native-env-builder/target/pip-build/terminado/





When I diff them, this is the first diff I see that I think matters (I
might be wrong about what matters though):

Both of them have this line:

    copying terminado/tests/basic_test.py -> build/lib/terminado/tests

But then they diverge after that line. In the 0.6 one, these are the next 3
lines:

    copying terminado/uimod_embed.js -> build/lib/terminado

    creating build/lib/terminado/_static

    copying terminado/_static/terminado.js -> build/lib/terminado/_static

But in the 0.7 one, this is the next line:

    error: can't copy 'terminado/_static': doesn't exist or not a regular
file

Things that seem notable:

In the 0.6 version, it tried to copy uimod_embed.js. No such attempt in
0.7. Could this copy have some side effect affecting _static?

In the 0.6 version, it attempted to create build/lib/terminado/_static, but
in the 0.7 version, it seemed to any to copy something. Is there a mkdir
that is missing?

In case it’s relevant:

Seans-MacBook-Pro-2:~/src/pepperdata11/native-env-builder/target%
./native-dev62-SNAPSHOT/bin/python --version
Python 2.7.11
Seans-MacBook-Pro-2:~/src/pepperdata11/native-env-builder/target%
./native-dev62-SNAPSHOT/bin/pip --version
pip 9.0.1 from
/Users/ssuchter/src/pepperdata11/native-env-builder/target/native-dev62-SNAPSHOT/lib/python2.7/site-packages
(python 2.7)

Sean


On December 13, 2017 at 2:49:09 AM, Thomas Kluyver (notifications@github.com)
wrote:

I also just tried pip install --no-use-wheel -b pip-build terminado==0.7 in
a fresh environment, and it ran happily. Not sure where to go on debugging
that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jupyter/terminado/issues/52#issuecomment-351355048>,
or mute
the thread

**Comment by takluyver** [comment]
Thanks for that detail. So I think the relevant difference is that in terminado 0.6, `package_data` looks like:

```python
{'terminado': ['uimod_embed.js', '_static/*']}
```

Whereas in 0.7, it's autogenerated, and looks like:

```python
{'': ['*'], 'terminado': ['_static/*']}
```

It's possible that this is a bug in distutils which was fixed between Python 2.7.11 and 2.7.14 (which I've just tested on).

**Comment by ssuchter** [comment]
I will see if updating to 2.7.14 solves this.

**Comment by ssuchter** [comment]
Indeed - on python 2.7.14 the issue disappears. Renaming this issue, I'll let you folks decide what you want to do with it.

**Comment by takluyver** [comment]
OK, thanks. In that case, I'm going to leave it as is. There should be two workarounds possible - either upgrade Python to a version with the fix, or allow pip to install a wheel (i.e. get rid of the `--no-use-wheel` flag).
