### ISSUE TITLE
Rename version `v` to something more descriptive

### ISSUE THREAD

**Issue by cphang99** [jupyter/terminado#71]
Currently, https://github.com/jupyter/terminado/releases/tag/v is labelled version `v`. I'm guessing that this corresponds to version 0.8.3 in pypi https://pypi.org/project/terminado/

We have a project (libreML) that takes jupyter and associated source dependencies, and depends on git tags for updating https://gitlab.com/libreml/libreml/merge_requests/127. It would be really helpful if there could be a new tag that corresponds to the version that is currently in pypi

Thanks very much.

**Comment by blink1073** [comment]
Fixed!
